language: cpp

os:
  - linux
  - osx
#  - windows

dist: focal
osx_image: xcode12  

#sudo: require

compiler:
  - clang
  - gcc

script:
  - cmake --version
  - cmake --help
  - cmake
  - ls -l
  - make
